name: Update list of PHP Docker Images

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: php-cs-fixer
          coverage: none
      -
        name: Checkout repository
        uses: actions/checkout@v6
      -
        name: Check PHP Coding Style
        run: php-cs-fixer --using-cache=no --diff check
      -
        name: Update list of PHP Docker images
        run: ./.github/workflows/update-data-file
      -
        name: Update README.md
        run: ./.github/workflows/update-readme
      -
        name: Check for changes
        id: git-check
        run: |
          if git diff --quiet; then
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            echo 'changed=true' >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT
      -
        name: Commit and push
        if: github.event_name != 'pull_request' && steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add --all
          git commit -m '[skip ci] Update PHP images matrix'
          git push
